### PR TITLE
U/cslage/com cam gain

### PR DESCRIPTION
**Pull request by craiglagegit**
This pull request has ~~three~~ two proposed changes:
(1) Updated policy/latiss/RXX.yaml with gain and noise values extracted using ptc.py from flats taken on the summit by Andrés Plazas.
(2) Updated policy/comcam/R22.yaml with gain and noise values extracted using ptc.py from flats taken in Tucson by Craig Lage.
~~(3) Updated policy/cameraHeader.yaml to correct assembly of the comCam raft.  Below shows the assembly using showCamera with the current file and with the proposed file.~~
This change was removed, since it is already fixed by DM-22506.
[ShowCamera_Firefly_10Mar19](https://user-images.githubusercontent.com/9419258/76358646-fcade680-62d6-11ea-99f2-ff2f54e83d24.png)
ShowCamera_Firefly_Existing_10Mar19

### CODE REVIEW

**Comment by craiglagegit** [comment]
Just in case it's not obvious, the current cameraHeader.yaml file gives the bottom Firefly image, which is scrambled.  The proposed cameraHeader.yaml file has a sign change on the y offset values, and gives the top Firefly image, which is correctly assembled.  I don't know whether these values also work for the lsstCam, and I also don't know whether the E2V offsets also will need correcting.

**Comment by SimonKrughoff** [comment]
> Just in case it's not obvious, the current cameraHeader.yaml file gives the bottom Firefly image, which is scrambled. The proposed cameraHeader.yaml file has a sign change on the y offset values, and gives the top Firefly image, which is correctly assembled. I don't know whether these values also work for the lsstCam, and I also don't know whether the E2V offsets also will need correcting.

@craiglagegit I already have changes to the yaml, that I think fixes the assembly issue in #153 of this repository.  I don't think changing the offsets, is the right answer here.  I am trying to get that merged today or tomorrow and then I'd appreciate you trying it out to see if it does what you want before we merge the geometry aspect of this PR.

**Comment by craiglagegit** [comment]
@SimonKrughoff .  OK, let me know where to get your updated yaml files.  I can test the assembly quite quickly.  I knew you were working on these yaml files, that's whay I put you as a reviewer.

**Comment by SimonKrughoff** [comment]
If you use branch `tickets/DM-22605` of this repository, you will get the new files.  You'll need to run `scons` to get the camera built.  Is that enough to go on?

**Comment by craiglagegit** [comment]
The tickets/DM-22605 branch of obs_lsst did in fact fix the image assembly issue. See attached.
ShowCamera_Firefly_DM-22605

**Comment by SimonKrughoff** [comment]
Excellent!  I am planning on merging today or tomorrow.

**Comment by craiglagegit** [comment]
I'll remove the change to cameraHeader.yaml from this pull request, since it will already be fixed by DM-22605.   I'm out of time for today, so I'll do this tomorrow.

**Comment by craiglagegit** [comment]
I've removed the change to policy/camerHeader.yaml

**Comment by timj** [comment]
@craiglagegit  can you please make a JIRA ticket for this work so that we have some record of why this is happening?

**Comment by craiglagegit** [comment]
Tim,

OK, will do.  I'm familiar with creating DM tickets.  Should this be a DM ticket, or somewhere else?

Thanks,
Craig
________________________________

**Comment by craiglagegit** [comment]
Never mind. I see a Commissioning Camera project.  I'll filr it there.

Craig
________________________________

**Comment by timj** [comment]
Was this pull request replaced by #292 ? If so can you please close this one?

**Pull request closed without merging**
