### PR TITLE
DM-17112: Allow detectorType to be overridden

### PR DESCRIPTION
**Pull request by SimonKrughoff**

### CODE REVIEW

**Comment by SimonKrughoff** [comment]
Apologies for the confusing branch name.  I accidentally named it for the epic rather than the story.  The ticket in the title of the PR is correct.

**Comment by SimonKrughoff** [comment]
I'll rename the branch on merge.

**Comment by mfisherlevine** [comment]
@RobertLuptonTheGood I looked this over and it looks OK to me, so you're off the hook unless you really want to review as well 🙂

**Comment by SimonKrughoff** [comment]
The merged branch for this PR is `tickets/DM-17112`.

**Pull request closed without merging**
